/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeemachinegiu;

import static coffeemachinegiu.MainCoffeeMachine.coffee;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class CaffieneMenu extends javax.swing.JFrame {

    /**
     * Creates new form CaffieneMenu
     */
    public CaffieneMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        caffeine = new javax.swing.JButton();
        caffeineDA = new javax.swing.JButton();
        caffeineDE = new javax.swing.JButton();
        caffeineSA = new javax.swing.JButton();
        caffeineSE = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(209, 199, 186));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(80, 48, 22));
        jPanel2.setForeground(new java.awt.Color(80, 48, 22));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeemachinegiu/imeges/icons8_java_bean_55px.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" COFFEINE");

        caffeine.setBackground(new java.awt.Color(211, 162, 113));
        caffeine.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        caffeine.setForeground(new java.awt.Color(80, 48, 22));
        caffeine.setText("Coffeine in All cupes");
        caffeine.setBorder(null);
        caffeine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffeineActionPerformed(evt);
            }
        });

        caffeineDA.setBackground(new java.awt.Color(211, 162, 113));
        caffeineDA.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        caffeineDA.setForeground(new java.awt.Color(80, 48, 22));
        caffeineDA.setText("Coffeine in double amricano");
        caffeineDA.setBorder(null);
        caffeineDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffeineDAActionPerformed(evt);
            }
        });

        caffeineDE.setBackground(new java.awt.Color(211, 162, 113));
        caffeineDE.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        caffeineDE.setForeground(new java.awt.Color(80, 48, 22));
        caffeineDE.setText(" Coffeine in double espresso");
        caffeineDE.setBorder(null);
        caffeineDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffeineDEActionPerformed(evt);
            }
        });

        caffeineSA.setBackground(new java.awt.Color(211, 162, 113));
        caffeineSA.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        caffeineSA.setForeground(new java.awt.Color(80, 48, 22));
        caffeineSA.setText("Coffeine in single amricano");
        caffeineSA.setBorder(null);
        caffeineSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffeineSAActionPerformed(evt);
            }
        });

        caffeineSE.setBackground(new java.awt.Color(211, 162, 113));
        caffeineSE.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        caffeineSE.setForeground(new java.awt.Color(80, 48, 22));
        caffeineSE.setText("Coffeine in single espresso");
        caffeineSE.setBorder(null);
        caffeineSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caffeineSEActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(71, 47, 35));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffeemachinegiu/imeges/icons8_exit_40px_2.png"))); // NOI18N
        jButton1.setActionCommand("");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(caffeineSA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caffeineSE, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caffeineDE, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caffeineDA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caffeine, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(caffeineSE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caffeineSA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caffeineDE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caffeineDA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(caffeine, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caffeineDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffeineDAActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"- The coffein in double amricano in all cupes today is: "
            + coffee.getCoffeineDoubleA());
    }//GEN-LAST:event_caffeineDAActionPerformed

    private void caffeineSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffeineSAActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"- The coffein in single amricano in all cupes today is: "
            + coffee.getCoffeineSingleA());
    }//GEN-LAST:event_caffeineSAActionPerformed

    private void caffeineDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffeineDEActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"- The coffein in double espresso in all cupes today is: "
            + coffee.getCoffeineDoubleE());
    }//GEN-LAST:event_caffeineDEActionPerformed

    private void caffeineSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffeineSEActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"-The coffein in single espresso in all cupes today is: "
            + coffee.getCoffeineSingleE());
    }//GEN-LAST:event_caffeineSEActionPerformed

    private void caffeineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caffeineActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"- The coffein in all cupes today is: "
            + coffee.getCoffeine());
    }//GEN-LAST:event_caffeineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaffieneMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaffieneMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaffieneMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaffieneMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaffieneMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caffeine;
    private javax.swing.JButton caffeineDA;
    private javax.swing.JButton caffeineDE;
    private javax.swing.JButton caffeineSA;
    private javax.swing.JButton caffeineSE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
